// Calibration export formats. All functions are pure (string in → string out) and unit-tested.
import { modelInfo } from './run.js';

export const FORMATS = [
  { id: 'opencv', label: 'OpenCV YAML', ext: 'yaml', mime: 'text/yaml', note: 'cv::FileStorage / cv2.FileStorage compatible.' },
  { id: 'json', label: 'JSON', ext: 'json', mime: 'application/json', note: 'Complete record (re-importable into CaliBoard).' },
  { id: 'ros', label: 'ROS camera_info', ext: 'yaml', mime: 'text/yaml', note: 'camera_calibration_parsers format for ROS 1 / ROS 2.' },
  { id: 'kalibr', label: 'Kalibr camchain', ext: 'yaml', mime: 'text/yaml', note: 'Kalibr / OpenVINS / VINS style camchain.' },
  { id: 'colmap', label: 'COLMAP', ext: 'txt', mime: 'text/plain', note: 'cameras.txt line; principal point shifted by +0.5 px to COLMAP’s pixel convention.' },
  { id: 'python', label: 'Python', ext: 'py', mime: 'text/x-python', note: 'NumPy arrays + an undistort() helper.' },
  { id: 'cpp', label: 'C++', ext: 'cpp', mime: 'text/x-c++src', note: 'cv::Mat definitions + undistortion.' },
];

/** Shortest round-trip number formatting, always with a decimal point (YAML/FileStorage reads reals). */
export function num(x) {
  if (!Number.isFinite(x)) return '0.';
  if (x === 0) return '0.';
  const s = String(x);
  return /[.eE]/.test(s) ? s : `${s}.`;
}
const plain = (x) => (Number.isFinite(x) ? String(x) : '0');

export function safeName(s, fallback = 'camera') {
  const n = String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
  return n || fallback;
}

function coeffs(result) {
  if (result.model === 'fisheye') return result.D.slice(0, 4);
  const want = { none: 5, radial2: 5, standard4: 5, standard5: 5, rational: 8, thinprism: 12, tilted: 14 }[result.distortion] || result.D.length;
  const d = result.D.slice(0, want);
  while (d.length < want) d.push(0);
  return d;
}

const isoDate = (ts) => new Date(ts || Date.now()).toISOString();

function cvMatrix(name, rows, cols, data, indent = '') {
  return `${indent}${name}: !!opencv-matrix\n${indent}   rows: ${rows}\n${indent}   cols: ${cols}\n${indent}   dt: d\n${indent}   data: [ ${data.map(num).join(', ')} ]\n`;
}

export function toOpenCV(result, { newK } = {}) {
  const D = coeffs(result);
  let out = '%YAML:1.0\n---\n';
  out += `calibration_time: "${isoDate(result.createdAt)}"\n`;
  out += `generator: "CaliBoard"\n`;
  if (result.name) out += `camera_name: "${String(result.name).replace(/"/g, "'")}"\n`;
  out += `image_width: ${result.imageSize.width}\nimage_height: ${result.imageSize.height}\n`;
  out += `camera_model: ${result.model}\n`;
  out += `distortion_model: "${result.model === 'fisheye' ? 'fisheye' : modelInfo(result.distortion).label}"\n`;
  if (result.model === 'fisheye') out += 'fisheye_model: 1\n';
  out += `nr_of_frames: ${result.views.length}\n`;
  out += cvMatrix('camera_matrix', 3, 3, result.K);
  out += cvMatrix('distortion_coefficients', 1, D.length, D);
  if (newK) out += cvMatrix('new_camera_matrix_alpha0', 3, 3, newK);
  out += `avg_reprojection_error: ${num(result.rms)}\n`;
  out += cvMatrix('per_view_reprojection_errors', result.views.length, 1, result.views.map((v) => v.rms));
  return out;
}

export function toROS(result, { name, newK } = {}) {
  const D = coeffs(result);
  const fisheye = result.model === 'fisheye';
  let model = 'plumb_bob';
  let d = D;
  if (fisheye) model = 'equidistant';
  else if (D.length > 5) { model = 'rational_polynomial'; d = D.slice(0, 8); }
  const P = newK || result.K;
  const list = (a) => `[${a.map(plain).join(', ')}]`;
  let out = '';
  if (!fisheye && D.length > 8) out += '# NOTE: thin-prism / tilt coefficients are not representable in camera_info and were dropped.\n';
  out += `image_width: ${result.imageSize.width}\nimage_height: ${result.imageSize.height}\n`;
  out += `camera_name: ${safeName(name || result.name)}\n`;
  out += `camera_matrix:\n  rows: 3\n  cols: 3\n  data: ${list(result.K)}\n`;
  out += `distortion_model: ${model}\n`;
  out += `distortion_coefficients:\n  rows: 1\n  cols: ${d.length}\n  data: ${list(d)}\n`;
  out += `rectification_matrix:\n  rows: 3\n  cols: 3\n  data: ${list([1, 0, 0, 0, 1, 0, 0, 0, 1])}\n`;
  out += `projection_matrix:\n  rows: 3\n  cols: 4\n  data: ${list([P[0], P[1], P[2], 0, P[3], P[4], P[5], 0, 0, 0, 1, 0])}\n`;
  return out;
}

export function toKalibr(result, { name } = {}) {
  const fisheye = result.model === 'fisheye';
  const D = coeffs(result);
  const K = result.K;
  const list = (a) => `[${a.map(plain).join(', ')}]`;
  let out = `# Kalibr camchain — generated by CaliBoard (${isoDate(result.createdAt)})\n`;
  const d = fisheye ? D.slice(0, 4) : D.slice(0, 4);
  if (!fisheye && D.slice(4).some((v) => Math.abs(v) > 1e-12)) out += '# NOTE: Kalibr radtan supports k1, k2, p1, p2 only; higher-order terms were dropped. Recalibrate with the "Standard" model for an exact match.\n';
  out += 'cam0:\n';
  out += `  camera_model: pinhole\n`;
  out += `  intrinsics: ${list([K[0], K[4], K[2], K[5]])}\n`;
  out += `  distortion_model: ${fisheye ? 'equidistant' : 'radtan'}\n`;
  out += `  distortion_coeffs: ${list(d)}\n`;
  out += `  resolution: [${result.imageSize.width}, ${result.imageSize.height}]\n`;
  out += `  rostopic: /${safeName(name || result.name, 'cam0')}/image_raw\n`;
  return out;
}

export function toCOLMAP(result) {
  const K = result.K, D = coeffs(result);
  const W = result.imageSize.width, H = result.imageSize.height;
  // COLMAP puts the centre of the top-left pixel at (0.5, 0.5); OpenCV puts it at (0, 0).
  const cx = K[2] + 0.5, cy = K[5] + 0.5;
  let model, params;
  if (result.model === 'fisheye') { model = 'OPENCV_FISHEYE'; params = [K[0], K[4], cx, cy, ...D.slice(0, 4)]; }
  else if (D.every((v) => Math.abs(v) < 1e-15)) { model = 'PINHOLE'; params = [K[0], K[4], cx, cy]; }
  else if (D.length <= 5 && Math.abs(D[4] || 0) < 1e-15) { model = 'OPENCV'; params = [K[0], K[4], cx, cy, D[0], D[1], D[2], D[3]]; }
  else { model = 'FULL_OPENCV'; const d = [...D.slice(0, 8)]; while (d.length < 8) d.push(0); params = [K[0], K[4], cx, cy, ...d]; }
  let out = '# Camera list with one line of data per camera:\n#   CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]\n# Number of cameras: 1\n';
  if (result.model !== 'fisheye' && D.length > 8) out += '# NOTE: thin-prism / tilt terms are not supported by COLMAP and were dropped.\n';
  out += `1 ${model} ${W} ${H} ${params.map(plain).join(' ')}\n`;
  return out;
}

export function toJSON(result) {
  const D = coeffs(result);
  const K = result.K;
  const out = {
    format: 'caliboard/calibration@1',
    name: result.name || '',
    created: isoDate(result.createdAt),
    camera: result.camera || null,
    image_size: { width: result.imageSize.width, height: result.imageSize.height },
    model: result.model,
    distortion_model: result.distortion,
    camera_matrix: [[K[0], K[1], K[2]], [K[3], K[4], K[5]], [K[6], K[7], K[8]]],
    distortion_coefficients: D,
    rms_reprojection_error: result.rms,
    std_devs: result.stdDevs || null,
    target: result.target || null,
    options: result.options || null,
    stats: result.stats ? { views: result.stats.views, points: result.stats.points, coverage: result.stats.coverage, removed_points: result.stats.removedPoints } : null,
    views: result.views.map((v) => ({ n: v.n, name: v.name || undefined, rms: v.rms, rvec: v.rvec, tvec: v.tvec, points: v.used })),
  };
  return `${JSON.stringify(out, null, 2)}\n`;
}

/** Parses a CaliBoard JSON export back into a result-like record (for the library). */
export function fromJSON(text) {
  const j = JSON.parse(text);
  if (!j || (j.format !== 'caliboard/calibration@1' && !j.camera_matrix)) throw new Error('Not a CaliBoard calibration JSON file');
  const K = j.camera_matrix.flat ? j.camera_matrix.flat() : j.camera_matrix;
  if (K.length !== 9 || !K.every(Number.isFinite)) throw new Error('camera_matrix must be 3×3 numbers');
  const D = (j.distortion_coefficients || []).map(Number);
  return {
    name: j.name || 'Imported calibration',
    createdAt: Date.parse(j.created) || Date.now(),
    camera: j.camera || { kind: 'import', label: 'Imported' },
    imageSize: { width: j.image_size.width, height: j.image_size.height },
    model: j.model === 'fisheye' ? 'fisheye' : 'pinhole',
    distortion: j.distortion_model || (j.model === 'fisheye' ? 'fisheye' : D.length > 5 ? 'rational' : 'standard5'),
    K, D,
    rms: Number(j.rms_reprojection_error) || 0,
    stdDevs: j.std_devs || null,
    target: j.target || null,
    options: j.options || {},
    views: (j.views || []).map((v) => ({ n: v.n, name: v.name, rms: v.rms, rvec: v.rvec, tvec: v.tvec, used: v.points, count: v.points })),
    stats: { views: (j.views || []).length, points: j.stats?.points || 0, coverage: j.stats?.coverage ?? null, removedPoints: j.stats?.removed_points || 0, progress: null },
    imported: true,
  };
}

/** Parses an OpenCV FileStorage YAML (as written above or by OpenCV's calibration sample). */
export function fromOpenCVYaml(text) {
  const mat = (key) => {
    const m = new RegExp(`${key}:\\s*!!opencv-matrix[\\s\\S]*?data:\\s*\\[([^\\]]*)\\]`).exec(text);
    return m ? m[1].split(',').map((s) => Number(s.trim())).filter((v) => Number.isFinite(v)) : null;
  };
  const int = (key) => { const m = new RegExp(`^${key}:\\s*(\\d+)`, 'm').exec(text); return m ? Number(m[1]) : null; };
  const K = mat('camera_matrix') || mat('K');
  const D = mat('distortion_coefficients') || mat('D') || [];
  const W = int('image_width'), H = int('image_height');
  if (!K || K.length !== 9 || !W || !H) throw new Error('Could not find camera_matrix, image_width and image_height in this YAML');
  const fisheye = /fisheye_model:\s*1|camera_model:\s*fisheye/.test(text);
  const rms = Number((/avg_reprojection_error:\s*([\d.eE+-]+)/.exec(text) || [])[1]) || 0;
  return {
    name: 'Imported (OpenCV YAML)', createdAt: Date.now(), camera: { kind: 'import', label: 'Imported' },
    imageSize: { width: W, height: H }, model: fisheye ? 'fisheye' : 'pinhole',
    distortion: fisheye ? 'fisheye' : D.length > 5 ? 'rational' : 'standard5', K, D, rms, stdDevs: null, target: null, options: {},
    views: [], stats: { views: 0, points: 0, coverage: null, removedPoints: 0, progress: null }, imported: true,
  };
}

const pyList = (a) => a.map(plain).join(', ');

export function toPython(result) {
  const K = result.K, D = coeffs(result), W = result.imageSize.width, H = result.imageSize.height;
  const fisheye = result.model === 'fisheye';
  const head = `# Camera calibration generated by CaliBoard (${isoDate(result.createdAt)})
# ${W}x${H}, ${fisheye ? 'fisheye (Kannala-Brandt)' : `pinhole, ${modelInfo(result.distortion).label} distortion`}, RMS reprojection error ${result.rms.toFixed(4)} px
import cv2
import numpy as np

IMAGE_SIZE = (${W}, ${H})  # (width, height) — intrinsics are only valid at this resolution
K = np.array([[${pyList(K.slice(0, 3))}],
              [${pyList(K.slice(3, 6))}],
              [${pyList(K.slice(6, 9))}]], dtype=np.float64)
`;
  if (fisheye) {
    return `${head}D = np.array([${pyList(D)}], dtype=np.float64).reshape(4, 1)


def undistort(img, balance=0.0):
    """balance=0 crops to valid pixels, balance=1 keeps the whole field of view."""
    h, w = img.shape[:2]
    new_K = cv2.fisheye.estimateNewCameraMatrixForUndistortRectify(K, D, (w, h), np.eye(3), balance=balance)
    map1, map2 = cv2.fisheye.initUndistortRectifyMap(K, D, np.eye(3), new_K, (w, h), cv2.CV_16SC2)
    return cv2.remap(img, map1, map2, interpolation=cv2.INTER_LINEAR)


def undistort_points(pts):
    """Pixel coordinates (N, 2) -> normalised, undistorted coordinates (N, 2)."""
    return cv2.fisheye.undistortPoints(np.asarray(pts, np.float64).reshape(-1, 1, 2), K, D).reshape(-1, 2)


if __name__ == "__main__":
    import sys
    image = cv2.imread(sys.argv[1])
    cv2.imwrite("undistorted.png", undistort(image))
`;
  }
  return `${head}dist = np.array([${pyList(D)}], dtype=np.float64)


def undistort(img, alpha=0.0):
    """alpha=0 crops to valid pixels, alpha=1 keeps every source pixel."""
    h, w = img.shape[:2]
    new_K, roi = cv2.getOptimalNewCameraMatrix(K, dist, (w, h), alpha, (w, h))
    return cv2.undistort(img, K, dist, None, new_K)


def undistort_points(pts):
    """Pixel coordinates (N, 2) -> normalised, undistorted coordinates (N, 2)."""
    return cv2.undistortPoints(np.asarray(pts, np.float64).reshape(-1, 1, 2), K, dist).reshape(-1, 2)


if __name__ == "__main__":
    import sys
    image = cv2.imread(sys.argv[1])
    cv2.imwrite("undistorted.png", undistort(image))
`;
}

export function toCpp(result) {
  const K = result.K, D = coeffs(result), W = result.imageSize.width, H = result.imageSize.height;
  const fisheye = result.model === 'fisheye';
  const list = (a) => a.map((v) => num(v)).join(', ');
  return `// Camera calibration generated by CaliBoard (${isoDate(result.createdAt)})
// ${W}x${H}, ${fisheye ? 'fisheye (Kannala-Brandt)' : 'pinhole'}, RMS reprojection error ${result.rms.toFixed(4)} px
#include <opencv2/opencv.hpp>

const cv::Size kImageSize(${W}, ${H});
const cv::Matx33d K(${list(K)});
const cv::Mat D = (cv::Mat_<double>(${fisheye ? 4 : 1}, ${fisheye ? 1 : D.length}) << ${list(D)});

cv::Mat undistort(const cv::Mat& img, double ${fisheye ? 'balance' : 'alpha'} = 0.0) {
  cv::Mat newK, map1, map2, out;
${fisheye
    ? `  cv::fisheye::estimateNewCameraMatrixForUndistortRectify(K, D, img.size(), cv::Matx33d::eye(), newK, balance);
  cv::fisheye::initUndistortRectifyMap(K, D, cv::Matx33d::eye(), newK, img.size(), CV_16SC2, map1, map2);`
    : `  newK = cv::getOptimalNewCameraMatrix(K, D, img.size(), alpha, img.size());
  cv::initUndistortRectifyMap(K, D, cv::Matx33d::eye(), newK, img.size(), CV_16SC2, map1, map2);`}
  cv::remap(img, out, map1, map2, cv::INTER_LINEAR);
  return out;
}
`;
}

export function exportAs(result, format, opts = {}) {
  switch (format) {
    case 'opencv': return toOpenCV(result, opts);
    case 'json': return toJSON(result, opts);
    case 'ros': return toROS(result, opts);
    case 'kalibr': return toKalibr(result, opts);
    case 'colmap': return toCOLMAP(result, opts);
    case 'python': return toPython(result, opts);
    case 'cpp': return toCpp(result, opts);
    default: throw new Error(`Unknown format ${format}`);
  }
}
